image: docker:18.02.0-ce-git

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker info
  - apk add --update py-pip && pip install docker-compose

pages_test:
  script:
    - (cd site; docker-compose run web bundle exec middleman build)
  except:
    - master

pages:
  script:
    - (cd site; docker-compose run web bundle exec middleman build)
    - cp -r site/public public
  artifacts:
    paths:
      - public
  only:
    - master
