image: docker/compose:1.19.0

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker info

site_test:
  script:
    - (cd site; docker-compose run web bundle exec middleman build)
  except:
    - master

site:
  script:
    - (cd site; docker-compose run web bundle exec middleman build)
    - cp site/public public
  artifacts:
    paths:
      - public
  only:
    - master
